### ISSUE TITLE
Unclear phrases in constitution

### ISSUE THREAD

**Issue by bkthomps** [ecesociety/Constitution#2]
Points 1 and 2 in `Section 2.4: Removal of Executive members` of the `ECE Society Constitution` are unclear.

**Comment by bkthomps** [comment]
@MatthewNielsen27 @KMFSousa

**Comment by KMFSousa** [comment]
What parts do you means specifically Bailey? is it:

> Resignation at their own discretion,
> Resignation` at the request of the membership, justified with reason as well as a petition with at least five percent (5%) of the total membership or fifty (50) members in accord,

It can be changed, but I wouldn't mind a suggestion on what exactly needs specifying here.

**Comment by bkthomps** [comment]
It's the resignation at the request of membership. Does this mean that the members can request a resignation? If so, it requires 5% of membership or 50 members in accord?

**Comment by KMFSousa** [comment]
@bkthomps Yes exactly, if the ECE students want to impeach an exec they can do so. You need 50 people or 5% whichever is less. 

The "whichever is less" should be specified more clearly though. It is implied but not specific.

Is there another point I'm missing?

**Comment by bkthomps** [comment]
Ok yeah that makes more sense. One more thing: does the request of membership mean that the person _has_ to resign, or is only highly suggested to? (From your comment I see it means impeach, but I didn't understand this without the comment)

**Comment by MatthewNielsen27** [comment]
Personally I think `resignation at the request of the membership` should mean that they must resign. Although, a forced resignation at 5% of the membership may seem a little low, and I think there is a possibility it could be done just for the meme. Maybe bumping the amount needed for a forced resignation to be a little higher, and then have a lower percentage be a `strong recommendation to resign`.

**Comment by KMFSousa** [comment]
Yes I agree with Matt, it’s meant to be an impeachment. Meaning they must leave that role and cannot be in another executive role.

5% works out to about 40-80 people depending on how many people are on term. So that should be enough. What do you think the total number of people should be?

To Baileys point, yes we should just make that more clear and straight up say impeachment.

**Comment by MatthewNielsen27** [comment]
@KMFSousa I just worry because it depends on how close your cohort is. I honestly think I could convince 40 people from my term to impeach someone for a meme.

**Comment by MatthewNielsen27** [comment]
@bkthomps @KMFSousa Have we arrived at a resolution?

**Comment by KMFSousa** [comment]
@MatthewNielsen27 I'm more then fine upping the percentage, and fixed value to avoid the meme. I like the idea of somehow including a note or something that says like if any impeachment process is started and gains support of more then X people the on and off executive team must review to see if they agree and would like to go forward with the impeachment. If over Y amount it is a clear stance of non-confience and the executive must step down.

We should change wording to include impeached and be more clear on the stuff Bailey mentioned above.

Did you want to make a pull for those @MatthewNielsen27 ?

**Comment by MatthewNielsen27** [comment]
I’ll add a PR tomorrow with these changes. What percentage do you think is
appropriate? 20?

**Comment by bkthomps** [comment]
@MatthewNielsen27 can we close this?
